"""
Sample Data Generator for Informatica PowerCenter Sources

This script reads Informatica metadata JSON (generated by infa_to_pyspark_parser.py)
and creates sample CSV files for all flat file sources.

The generated data respects:
- Field data types (string, number, date, etc.)
- Field precision and scale
- Realistic sample values based on field names
- Proper CSV formatting with headers

Usage:
    uv run generate_sample_data.py metadata.json [num_rows] [output_dir]
    
Examples:
    uv run generate_sample_data.py complex5_metadata.json
    uv run generate_sample_data.py complex5_metadata.json 500 my_data
"""

import json
import csv
import random
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Any
import sys


class SampleDataGenerator:
    """Generates realistic sample data based on Informatica metadata"""
    
    def __init__(self, num_rows: int = 100):
        self.num_rows = num_rows
        
        # Sample data pools for realistic generation
        self.first_names = [
            "John", "Jane", "Michael", "Sarah", "David", "Emily", "Robert", "Lisa",
            "James", "Mary", "William", "Patricia", "Richard", "Jennifer", "Thomas",
            "Linda", "Charles", "Barbara", "Daniel", "Susan", "Matthew", "Jessica",
            "Christopher", "Nancy", "Joseph", "Karen", "Mark", "Betty", "Donald", "Helen"
        ]
        
        self.last_names = [
            "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
            "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez",
            "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
            "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark"
        ]
        
        self.jobs = [
            "Manager", "Analyst", "Developer", "Engineer", "Consultant", "Director",
            "Specialist", "Coordinator", "Administrator", "Supervisor", "Associate",
            "Architect", "Designer", "Technician", "Clerk", "President", "Salesman"
        ]
        
        self.departments = [
            "Sales", "Marketing", "Engineering", "Finance", "HR", "Operations",
            "IT", "Customer Service", "Research", "Legal", "Accounting", "Production"
        ]
        
        self.locations = [
            "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia",
            "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Seattle",
            "Boston", "Denver", "Miami", "Atlanta", "Portland", "Detroit"
        ]
        
        self.genders = ["Male", "Female"]
        self.gender_codes = ["M", "F"]
        self.yes_no = ["Yes", "No"]
        self.yes_no_short = ["Y", "N"]
        
        # Telecom-specific data
        self.contract_types = ["Month-to-month", "One year", "Two year"]
        self.payment_methods = [
            "Electronic check", "Mailed check", "Bank transfer (automatic)",
            "Credit card (automatic)"
        ]
        self.internet_services = ["DSL", "Fiber optic", "No"]
        self.phone_services = ["Yes", "No"]
        self.multiple_lines = ["Yes", "No", "No phone service"]
        self.online_services = ["Yes", "No", "No internet service"]
    
    def _generate_value(self, field: Dict[str, Any], row_index: int) -> Any:
        """Generate a sample value based on field metadata"""
        field_name = field['name'].upper()
        datatype = field.get('datatype', 'string').lower()
        precision = field.get('precision')
        scale = field.get('scale')
        
        # ===== ID Fields =====
        if any(x in field_name for x in ['EMPNO', 'EMPID', 'EMPLOYEE_ID', 'EMP_NO']):
            return 1000 + row_index
        
        if 'CUSTOMERID' in field_name or 'CUSTOMER_ID' in field_name:
            return f"{1000 + row_index}-ABCDE"[:(int(precision) if precision else 10)]
        
        if 'DEPTNO' in field_name or 'DEPT_NO' in field_name or 'DEPID' in field_name:
            return random.choice([10, 20, 30, 40, 50])
        
        # ===== Name Fields =====
        if 'FIRSTNAME' in field_name or 'FIRST_NAME' in field_name:
            return random.choice(self.first_names)
        
        if 'LASTNAME' in field_name or 'LAST_NAME' in field_name:
            return random.choice(self.last_names)
        
        if 'ENAME' in field_name and 'DEPT' not in field_name:
            return random.choice(self.first_names)
        
        if 'DNAME' in field_name or 'DEPT_NAME' in field_name:
            return random.choice(self.departments)
        
        # ===== Contact Fields =====
        if 'EMAIL' in field_name:
            first = random.choice(self.first_names).lower()
            last = random.choice(self.last_names).lower()
            domains = ['company.com', 'email.com', 'work.com', 'business.com']
            return f"{first}.{last}@{random.choice(domains)}"
        
        if 'PHONE' in field_name and 'SERVICE' not in field_name:
            return f"{random.randint(200, 999)}-{random.randint(100, 999)}-{random.randint(1000, 9999)}"
        
        # ===== Job/Position Fields =====
        if 'JOB' in field_name or 'POSITION' in field_name:
            return random.choice(self.jobs)
        
        # ===== Location Fields =====
        if 'LOC' in field_name or 'LOCATION' in field_name or 'CITY' in field_name:
            return random.choice(self.locations)
        
        # ===== Gender Fields =====
        if 'GENDER' in field_name:
            if precision and int(precision) <= 1:
                return random.choice(self.gender_codes)
            return random.choice(self.genders)
        
        # ===== Financial Fields =====
        if 'SALARY' in field_name or field_name == 'SAL':
            return round(random.uniform(30000, 150000), int(scale) if scale else 2)
        
        if 'COMM' in field_name or 'COMMISSION' in field_name:
            return round(random.uniform(0, 10000), int(scale) if scale else 2) if random.random() > 0.3 else 0
        
        if 'CHARGES' in field_name and 'MONTHLY' in field_name:
            return round(random.uniform(18.95, 118.95), 2)
        
        if 'CHARGES' in field_name and 'TOTAL' in field_name:
            months = random.randint(1, 72)
            monthly = random.uniform(18.95, 118.95)
            return round(months * monthly, 2)
        
        # ===== Manager/Hierarchy Fields =====
        if 'MGR' in field_name or 'MANAGER' in field_name:
            return random.randint(1000, 1050)
        
        # ===== Telecom-Specific Fields =====
        if 'SENIORCITIZEN' in field_name or 'SENIOR_CITIZEN' in field_name:
            return random.choice([0, 1])
        
        if 'PARTNER' in field_name:
            return random.choice(self.yes_no)
        
        if 'DEPENDENT' in field_name:
            return random.choice(self.yes_no)
        
        if 'TENURE' in field_name:
            return random.randint(0, 72)
        
        if 'PHONESERVICE' in field_name or 'PHONE_SERVICE' in field_name:
            return random.choice(self.phone_services)
        
        if 'MULTIPLELINES' in field_name or 'MULTIPLE_LINES' in field_name:
            return random.choice(self.multiple_lines)
        
        if 'INTERNETSERVICE' in field_name or 'INTERNET_SERVICE' in field_name:
            return random.choice(self.internet_services)
        
        if any(x in field_name for x in ['ONLINESECURITY', 'ONLINEBACKUP', 'DEVICEPROTECTION', 
                                          'TECHSUPPORT', 'STREAMINGTV', 'STREAMINGMOVIES']):
            return random.choice(self.online_services)
        
        if 'CONTRACT' in field_name:
            return random.choice(self.contract_types)
        
        if 'PAPERLESSBILLING' in field_name or 'PAPERLESS_BILLING' in field_name:
            return random.choice(self.yes_no)
        
        if 'PAYMENTMETHOD' in field_name or 'PAYMENT_METHOD' in field_name:
            return random.choice(self.payment_methods)
        
        if 'CHURN' in field_name:
            return random.choice(self.yes_no)
        
        # ===== Generic Type Fields =====
        if 'TYPE' in field_name and len(field_name) <= 10:
            if precision and int(precision) <= 1:
                return random.choice(['A', 'B', 'C', 'D'])
            return random.choice(['Type A', 'Type B', 'Type C'])
        
        # ===== Datatype-based Generation =====
        if 'string' in datatype or 'varchar' in datatype or 'char' in datatype:
            max_length = int(precision) if precision else 20
            
            # Generate realistic string based on length
            if max_length <= 1:
                return random.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
            elif max_length <= 5:
                return ''.join(random.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=min(max_length, 5)))
            elif max_length <= 10:
                return f"VAL{row_index:04d}"
            else:
                return f"Value_{row_index}_{random.randint(100, 999)}"[:max_length]
        
        if 'number' in datatype or 'decimal' in datatype or 'integer' in datatype or 'double' in datatype:
            prec = int(precision) if precision else 10
            scl = int(scale) if scale else 0
            
            if scl > 0:
                # Decimal number
                max_val = 10 ** (prec - scl)
                return round(random.uniform(0, max_val - 1), scl)
            else:
                # Integer
                max_val = 10 ** min(prec, 9)
                return random.randint(0, max_val - 1)
        
        if 'date' in datatype:
            start_date = datetime(2020, 1, 1)
            random_days = random.randint(0, 1460)  # 4 years
            return (start_date + timedelta(days=random_days)).strftime('%Y-%m-%d')
        
        if 'timestamp' in datatype:
            start_date = datetime(2020, 1, 1)
            random_seconds = random.randint(0, 126230400)  # 4 years
            return (start_date + timedelta(seconds=random_seconds)).strftime('%Y-%m-%d %H:%M:%S')
        
        # Default fallback
        return f"Data_{row_index}"
    
    def generate_csv_for_source(self, source: Dict[str, Any], output_dir: Path) -> str:
        """Generate a CSV file for a given source"""
        source_name = source['name']
        source_type = source['type']
        is_flat_file = source.get('is_flat_file', False)
        fields = source.get('fields', [])
        
        if not is_flat_file:
            print(f"⏭️  Skipping {source_name} (Database source - {source_type})")
            return None
        
        if not fields:
            print(f"⚠️  Skipping {source_name} (No fields defined)")
            return None
        
        # Create output directory
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Generate filename
        output_file = output_dir / f"{source_name.lower()}.csv"
        
        print(f"📝 Generating {source_name}.csv with {self.num_rows} rows...")
        
        # Extract field names for header
        field_names = [field['name'] for field in fields]
        
        # Generate data rows
        rows = []
        for i in range(self.num_rows):
            row = []
            for field in fields:
                value = self._generate_value(field, i)
                row.append(value)
            rows.append(row)
        
        # Write to CSV
        with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(field_names)  # Header
            writer.writerows(rows)
        
        print(f"   ✅ Created: {output_file} ({len(field_names)} columns × {self.num_rows} rows)")
        return str(output_file)
    
    def generate_all_sources(self, metadata: Dict[str, Any], output_dir: str = "generated/sample_data") -> List[str]:
        """Generate CSV files for all flat file sources in metadata"""
        output_path = Path(output_dir)
        sources = metadata.get('sources', [])
        
        if not sources:
            print("❌ No sources found in metadata")
            return []
        
        print(f"\n{'='*80}")
        print(f"SAMPLE DATA GENERATION")
        print(f"{'='*80}\n")
        print(f"📂 Output directory: {output_path.absolute()}")
        print(f"📊 Rows per file: {self.num_rows}")
        print(f"📥 Total sources: {len(sources)}\n")
        
        generated_files = []
        flat_file_count = 0
        
        for source in sources:
            if source.get('is_flat_file', False):
                flat_file_count += 1
                result = self.generate_csv_for_source(source, output_path)
                if result:
                    generated_files.append(result)
        
        print(f"\n{'='*80}")
        print(f"✅ Generated {len(generated_files)} CSV file(s) from {flat_file_count} flat file source(s)")
        print(f"{'='*80}\n")
        
        return generated_files


def main():
    """Main function"""
    if len(sys.argv) < 2:
        print("Usage: uv run generate_sample_data.py <metadata.json> [num_rows] [output_dir]")
        print("\nExamples:")
        print("  uv run generate_sample_data.py generated/metadata/complex5_metadata.json")
        print("  uv run generate_sample_data.py generated/metadata/complex5_metadata.json 500")
        print("  uv run generate_sample_data.py generated/metadata/complex5_metadata.json 500 custom_dir")
        print("\nDefault output: generated/sample_data/")
        print("\nDescription:")
        print("  Generates sample CSV files for all flat file sources defined in the metadata JSON.")
        print("  The metadata JSON should be generated using infa_to_pyspark_parser.py")
        sys.exit(1)
    
    metadata_file = sys.argv[1]
    num_rows = int(sys.argv[2]) if len(sys.argv) > 2 else 100
    output_dir = sys.argv[3] if len(sys.argv) > 3 else "generated/sample_data"
    
    # Load metadata
    try:
        with open(metadata_file, 'r') as f:
            metadata = json.load(f)
    except FileNotFoundError:
        print(f"❌ Error: Metadata file not found: {metadata_file}")
        print("\nFirst generate metadata using:")
        print(f'  uv run infa_to_pyspark_parser.py "Informatica PC Samples/<file>.xml" metadata.json')
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ Error: Invalid JSON in {metadata_file}: {e}")
        sys.exit(1)
    
    # Generate sample data
    generator = SampleDataGenerator(num_rows=num_rows)
    generated_files = generator.generate_all_sources(metadata, output_dir)
    
    if generated_files:
        print("📁 Generated files:")
        for file in generated_files:
            print(f"   • {file}")
        print(f"\n💡 Tip: Use these CSV files to test your generated PySpark code!")
    else:
        print("⚠️  No CSV files were generated. Check if your metadata contains flat file sources.")


if __name__ == "__main__":
    main()
